name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.results.outputs.version }}
      commit: ${{ steps.results.outputs.commit }}
    steps:
      - name: '📚 Checkout'
        uses: actions/checkout@v2
      - name: get current commit hash
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: '🧩 Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@adnan808'
      - name: '🚀 Install pnpm'
        run: npm add -g pnpm
      - name: '🚀 Install packages'
        run: pnpm install
      - name: '🚀 Build'
        run: tsc --build
      - name: '🚀 Publish'
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - id: results
        run: |
          echo "::set-output name=version::$(jq -r .version ./package.json)"
          echo "::set-output name=commit::https://github.com/dashdevs/${{ github.event.repository.name }}/commit/${{ env.commit_hash }}"
